name: Build test
on: [push, pull_request]

jobs:
  test-windows:
    name: Test changes
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: true

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Test
        run: go test -v